### ISSUE TITLE
npm install without bower fails

### ISSUE THREAD

**Issue by Tzaphkiel** [jonmiles/react-bootstrap-treeview#13]
I am on windows and all other packages so far worked. This one seems to depend on bower for the installation. There should be a way to distribute the module in npmjs without having a dependency to bower...

```
myProjectPath>npm install react-bootstrap-treeview --save

> react-bootstrap-treeview@0.1.0 install myProjectPath\node_modules\react-bootstrap-treeview
> bower install

'bower' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "F:\\nodejs\\node.exe" "j:\\node-modules\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-bootstrap-treeview" "--save"
npm ERR! node v5.7.1
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! react-bootstrap-treeview@0.1.0 install: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-bootstrap-treeview@0.1.0 install script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-bootstrap-treeview package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-bootstrap-treeview
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-bootstrap-treeview
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     myProjectPath\npm-debug.log
```

In the  npm-debug.log, you can just see that the bower install is not wirking because it cannot spawn the bower process:

```
2348 verbose stack Error: react-bootstrap-treeview@0.1.0 install: `bower install`
2348 verbose stack Exit status 1
2348 verbose stack     at EventEmitter.<anonymous> (j:\node-modules\node_modules\npm\lib\utils\lifecycle.js:232:16)
2348 verbose stack     at emitTwo (events.js:100:13)
2348 verbose stack     at EventEmitter.emit (events.js:185:7)
2348 verbose stack     at ChildProcess.<anonymous> (j:\node-modules\node_modules\npm\lib\utils\spawn.js:24:14)
2348 verbose stack     at emitTwo (events.js:100:13)
2348 verbose stack     at ChildProcess.emit (events.js:185:7)
2348 verbose stack     at maybeClose (internal/child_process.js:827:16)
2348 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

This package works fine and is a derivative of this one I believe:
https://github.com/eliftech/treeview-react-bootstrap

**Comment by Tzaphkiel** [comment]
It seems this repository is not active anymore...
